name: deploy to lambda
on:
  push :
    branches: [ main ]
jobs:
  deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: AWS Configure 
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-east-1'
      - name: AWS S3 Command 
        run: |
          aws s3 ls
















